name: Ubuntu CI Flaky Tests Report

on:
  workflow_dispatch:
    inputs:
      os-image:
        description: 'The OS image for the workflow'
        required: false
        type: string
        default: 'ubuntu-22.04'
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  detect-flaky:
    runs-on: ${{ inputs.os-image }}
    steps:

      - name: Sync eProsima/Fast-DDS repository
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          path: src/flaky_test_infra_poc
          ref: 'main'

      - name: Install Python dependencies
        run: |
          pip install pytest pytest-json-report requests vcstool lxml junitparser pandas numpy seaborn

      - name: Download previous test results with plugin
        if: always()
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ubuntu-ci.yml
          name: test-results-all
          workflow_conclusion: completed

      - name: Flaky test analysis - grouping by [window-size] runs - [window-size]*[window-count] runs history
        id: flaky_analysis
        run: |
          python ${{ github.workspace }}/src/flaky_test_infra_poc/resources/check_flakes.py --junit-files=. --grouping-option=runs --window-size=5 --window-count=1 --top-n=6 --output-file=$GITHUB_STEP_SUMMARY

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: flaky_tests_report
          path: |
            flaky_tests_report.txt
